# Generated by Django 5.2.7 on 2025-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name.', max_length=150, unique=True)),
                ('description', models.TextField(help_text='Location description.')),
                ('type', models.CharField(choices=[('HIST', 'Historical Site'), ('MUSE', 'Museum'), ('NATE', 'Natural Landmark'), ('VENU', 'Venue/Activity'), ('REST', 'Restaurant/Food'), ('OTHR', 'Other')], default='OTHR', help_text='Location category.', max_length=4)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Geographical latitude.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Geographical longitude.', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
